#!/bin/bash
# Set up demo infrastructure (emulators, user)
#
# Usage:
#   ./demo/setup-infrastructure.sh [--reset]
#
# Options:
#   --reset    Force recreate demo user even if exists
#
# After running this, use:
#   ./demo/run-http-demo.sh     # For Gradio HTTP demo
#   ./demo/run-pubsub-demo.sh   # For Pub/Sub CLI demo

set -e

cd "$(dirname "$0")/.."

# Parse arguments
RESET_FLAG=""
for arg in "$@"; do
    case $arg in
        --reset)
            RESET_FLAG="--reset"
            ;;
    esac
done

echo "=== Demo Infrastructure Setup ==="
echo ""

# Load environment variables
if [ -f .env ]; then
    echo "Loading .env file..."
    set -a
    source .env
    set +a
fi

# Configuration
STORAGE_DIR=${STORAGE_DIR:-./data/agents}
PUBSUB_EMULATOR_PORT=${PUBSUB_EMULATOR_PORT:-8085}
PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID:-"demo-project"}

# Check if Pub/Sub emulator is already running
PUBSUB_RUNNING=false

if docker ps --format '{{.Names}}' | grep -q "^pubsub-emulator-demo$"; then
    PUBSUB_RUNNING=true
fi

# Start Pub/Sub emulator if not running
if [ "$PUBSUB_RUNNING" = true ]; then
    echo "Pub/Sub emulator already running on port $PUBSUB_EMULATOR_PORT"
else
    echo "Starting Pub/Sub emulator on port $PUBSUB_EMULATOR_PORT..."
    docker rm -f pubsub-emulator-demo 2>/dev/null || true
    docker run -d \
        --name pubsub-emulator-demo \
        -p ${PUBSUB_EMULATOR_PORT}:8085 \
        google/cloud-sdk:emulators \
        /bin/bash -c "gcloud beta emulators pubsub start --project=${PUBSUB_PROJECT_ID} --host-port=0.0.0.0:8085"

    echo "Waiting for Pub/Sub emulator..."
    sleep 5
fi

# Create Pub/Sub infrastructure
echo "Ensuring Pub/Sub infrastructure exists..."
PUBSUB_EMULATOR_HOST="localhost:${PUBSUB_EMULATOR_PORT}" uv run python << EOF
import os
os.environ["PUBSUB_EMULATOR_HOST"] = "localhost:${PUBSUB_EMULATOR_PORT}"

from google.cloud import pubsub_v1

project_id = "${PUBSUB_PROJECT_ID}"
publisher = pubsub_v1.PublisherClient()
subscriber = pubsub_v1.SubscriberClient()

# Create topics
for topic_name in ["agent-requests", "agent-responses"]:
    topic_path = f"projects/{project_id}/topics/{topic_name}"
    try:
        publisher.create_topic(request={"name": topic_path})
        print(f"  Created topic: {topic_name}")
    except Exception:
        print(f"  Topic exists: {topic_name}")

# Create subscriptions
subs = [
    ("agent-requests-sub", "agent-requests"),
    ("agent-responses-sub", "agent-responses"),
]
for sub_name, topic_name in subs:
    sub_path = f"projects/{project_id}/subscriptions/{sub_name}"
    topic_path = f"projects/{project_id}/topics/{topic_name}"
    try:
        subscriber.create_subscription(request={"name": sub_path, "topic": topic_path})
        print(f"  Created subscription: {sub_name}")
    except Exception:
        print(f"  Subscription exists: {sub_name}")
EOF

# Create local storage directory
mkdir -p "$STORAGE_DIR"

# Create demo user
echo ""
echo "=== Setting up Demo User ==="
AGENT_DIR="$STORAGE_DIR/demo-user"
if [ "$RESET_FLAG" = "--reset" ] || [ ! -d "$AGENT_DIR" ]; then
    mkdir -p "$AGENT_DIR"
    echo "# Identity" > "$AGENT_DIR/me.md"
    echo "# Context Anchors" > "$AGENT_DIR/context_anchors.md"
    echo "# Current Session" > "$AGENT_DIR/current_session.md"
    echo "Demo user created."
else
    echo "Demo user already exists."
fi

# Write environment file for demo scripts to source
cat > demo/demo.env << EOF
# Generated by setup-infrastructure.sh - source this in demo scripts
export STORAGE_DIR="${STORAGE_DIR}"
export PUBSUB_EMULATOR_HOST="localhost:${PUBSUB_EMULATOR_PORT}"
export PUBSUB_PROJECT_ID="${PUBSUB_PROJECT_ID}"
export PUBSUB_REQUEST_SUBSCRIPTION="projects/${PUBSUB_PROJECT_ID}/subscriptions/agent-requests-sub"
export PUBSUB_RESPONSE_TOPIC="projects/${PUBSUB_PROJECT_ID}/topics/agent-responses"
EOF

echo ""
echo "==========================================="
echo "  Infrastructure Ready!"
echo "==========================================="
echo ""
echo "  Storage:        $STORAGE_DIR"
echo "  Pub/Sub:        localhost:$PUBSUB_EMULATOR_PORT"
echo "  Demo User:      demo-user"
echo ""
echo "  Run demos with:"
echo "    ./demo/run-http-demo.sh     # Gradio HTTP demo"
echo "    ./demo/run-pubsub-demo.sh   # Pub/Sub CLI demo"
echo ""
echo "  Stop infrastructure with:"
echo "    ./demo/stop-infrastructure.sh"
echo "==========================================="
