#!/bin/bash
# Set up demo infrastructure (emulators, bucket, topics, user)
#
# Usage:
#   ./demo/setup-infrastructure.sh [--reset]
#
# Options:
#   --reset    Force recreate demo user even if exists
#
# After running this, use:
#   ./demo/run-http-demo.sh     # For Gradio HTTP demo
#   ./demo/run-pubsub-demo.sh   # For Pub/Sub CLI demo

set -e

cd "$(dirname "$0")/.."

# Parse arguments
RESET_FLAG=""
for arg in "$@"; do
    case $arg in
        --reset)
            RESET_FLAG="--reset"
            ;;
    esac
done

echo "=== Demo Infrastructure Setup ==="
echo ""

# Load environment variables
if [ -f .env ]; then
    echo "Loading .env file..."
    set -a
    source .env
    set +a
fi

# Configuration
GCS_EMULATOR_PORT=${GCS_EMULATOR_PORT:-4443}
GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-"deep-agent-memory"}
PUBSUB_EMULATOR_PORT=${PUBSUB_EMULATOR_PORT:-8085}
PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID:-"demo-project"}

# Check if emulators are already running
GCS_RUNNING=false
PUBSUB_RUNNING=false

if docker ps --format '{{.Names}}' | grep -q "^gcs-emulator-demo$"; then
    GCS_RUNNING=true
fi

if docker ps --format '{{.Names}}' | grep -q "^pubsub-emulator-demo$"; then
    PUBSUB_RUNNING=true
fi

# Start GCS emulator if not running
if [ "$GCS_RUNNING" = true ]; then
    echo "GCS emulator already running on port $GCS_EMULATOR_PORT"
else
    echo "Starting GCS emulator on port $GCS_EMULATOR_PORT..."
    docker rm -f gcs-emulator-demo 2>/dev/null || true
    docker run -d \
        --name gcs-emulator-demo \
        -p ${GCS_EMULATOR_PORT}:4443 \
        -v gcs-demo-data:/data \
        fsouza/fake-gcs-server \
        -scheme http \
        -port 4443 \
        -filesystem-root /data \
        -data /data

    # Wait for GCS emulator
    echo "Waiting for GCS emulator..."
    for i in {1..10}; do
        if curl -s "http://localhost:${GCS_EMULATOR_PORT}/storage/v1/b" > /dev/null 2>&1; then
            echo "GCS emulator is ready."
            break
        fi
        if [ $i -eq 10 ]; then
            echo "ERROR: GCS emulator failed to start"
            exit 1
        fi
        sleep 1
    done
fi

# Start Pub/Sub emulator if not running
if [ "$PUBSUB_RUNNING" = true ]; then
    echo "Pub/Sub emulator already running on port $PUBSUB_EMULATOR_PORT"
else
    echo "Starting Pub/Sub emulator on port $PUBSUB_EMULATOR_PORT..."
    docker rm -f pubsub-emulator-demo 2>/dev/null || true
    docker run -d \
        --name pubsub-emulator-demo \
        -p ${PUBSUB_EMULATOR_PORT}:8085 \
        google/cloud-sdk:emulators \
        /bin/bash -c "gcloud beta emulators pubsub start --project=${PUBSUB_PROJECT_ID} --host-port=0.0.0.0:8085"

    echo "Waiting for Pub/Sub emulator..."
    sleep 5
fi

# Create GCS bucket (idempotent - ignores if exists)
echo "Ensuring GCS bucket exists: $GCS_BUCKET_NAME..."
curl -s -X POST "http://localhost:${GCS_EMULATOR_PORT}/storage/v1/b?project=local-project" \
    -H "Content-Type: application/json" \
    -d "{\"name\": \"${GCS_BUCKET_NAME}\"}" > /dev/null 2>&1 || true

# Create Pub/Sub infrastructure
echo "Ensuring Pub/Sub infrastructure exists..."
PUBSUB_EMULATOR_HOST="localhost:${PUBSUB_EMULATOR_PORT}" python3 << EOF
import os
os.environ["PUBSUB_EMULATOR_HOST"] = "localhost:${PUBSUB_EMULATOR_PORT}"

from google.cloud import pubsub_v1

project_id = "${PUBSUB_PROJECT_ID}"
publisher = pubsub_v1.PublisherClient()
subscriber = pubsub_v1.SubscriberClient()

# Create topics
for topic_name in ["agent-requests", "agent-responses"]:
    topic_path = f"projects/{project_id}/topics/{topic_name}"
    try:
        publisher.create_topic(request={"name": topic_path})
        print(f"  Created topic: {topic_name}")
    except Exception:
        print(f"  Topic exists: {topic_name}")

# Create subscriptions
subs = [
    ("agent-requests-sub", "agent-requests"),
    ("agent-responses-sub", "agent-responses"),
]
for sub_name, topic_name in subs:
    sub_path = f"projects/{project_id}/subscriptions/{sub_name}"
    topic_path = f"projects/{project_id}/topics/{topic_name}"
    try:
        subscriber.create_subscription(request={"name": sub_path, "topic": topic_path})
        print(f"  Created subscription: {sub_name}")
    except Exception:
        print(f"  Subscription exists: {sub_name}")
EOF

# Create demo user (respects --reset flag)
echo ""
echo "=== Setting up Demo User ==="
./scripts/create-user.sh demo-user $RESET_FLAG

# Write environment file for demo scripts to source
cat > demo/demo.env << EOF
# Generated by setup-infrastructure.sh - source this in demo scripts
export STORAGE_EMULATOR_HOST="http://localhost:${GCS_EMULATOR_PORT}"
export GCS_BUCKET_NAME="${GCS_BUCKET_NAME}"
export PUBSUB_EMULATOR_HOST="localhost:${PUBSUB_EMULATOR_PORT}"
export PUBSUB_PROJECT_ID="${PUBSUB_PROJECT_ID}"
export PUBSUB_REQUEST_SUBSCRIPTION="projects/${PUBSUB_PROJECT_ID}/subscriptions/agent-requests-sub"
export PUBSUB_RESPONSE_TOPIC="projects/${PUBSUB_PROJECT_ID}/topics/agent-responses"
EOF

echo ""
echo "==========================================="
echo "  Infrastructure Ready!"
echo "==========================================="
echo ""
echo "  GCS Emulator:   http://localhost:$GCS_EMULATOR_PORT"
echo "  Pub/Sub:        localhost:$PUBSUB_EMULATOR_PORT"
echo "  Demo User:      demo-user"
echo ""
echo "  Run demos with:"
echo "    ./demo/run-http-demo.sh     # Gradio HTTP demo"
echo "    ./demo/run-pubsub-demo.sh   # Pub/Sub CLI demo"
echo ""
echo "  Stop infrastructure with:"
echo "    ./demo/stop-infrastructure.sh"
echo "==========================================="
